heat_template_version: 2014-10-16

description: setup CernVM-FS Stratum 0 server

resources:
  vm_os:
    type: cvmfs.yaml
    properties:
      key_name: mtangaro-key
      vm_name: cvmfs_server
      image_id: 9ba220c2-7205-484b-bd19-d4af8194d298 # ubuntu 16.04
      #image_id: bd2ebc86-7930-4f90-af7b-ff94b982a2eb # CentOS 7
      #image_id: 97da99b8-2007-4e5c-b244-665ee970941a # Ubuntu 16.04 Heat Enabled
      instance_type: medium #4cpu-4GB-20dsk
      availability_zone: nova
      vol1_size: 100
      vol1_mountpoint: /var/spool/cvmfs
      vol2_size: 200
      vol2_mountpoint: /srv/cvmfs
      net_id: fe82ef7b-4bb7-4c1e-b4ec-ec5c1b0c7333 #pub-ip
