heat_template_version: 2014-10-16

description: >
  This template deploy a CernVM-FS Stratum Zero server


##################################
parameters:
  key_name:
    type: string
    description: Name of a KeyPair
    default: ROBOT
  vm_name:
    type: string
    label: VM name
    default: cvmfs-stack
  image_id:
    type: string
    label: Image ID
    description: "Ubuntu 16.04"
    default: 9ba220c2-7205-484b-bd19-d4af8194d298
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: small
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
    default: nova
  spool_size:
    type: number
    description: Size of the volume to be created.
    default: 1
  spool_mountpoint:
    type: string
    description: The directory to provide to the user
    default: /var/spool/cvmfs
  srv_size:
    type: number
    description: Size of the volume to be created.
    default: 1
  srv_mountpoint:
    type: string
    description: The directory to provide to the user
    default: /srv/cvmfs
  net_id:
    type: string
    description: ID of public sub network into which servers get deployed
    default: fe82ef7b-4bb7-4c1e-b4ec-ec5c1b0c7333

resources:

  #________________________________
  # CernVM-FS software configuration
  cvmfs_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: spool_mountpoint
      - name: spool_volid
      - name: srv_mountpoint
      - name: srv_volid
      config: { get_file: setup.sh }

  cvmfs_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: cvmfs_config}
      server: {get_resource: cvmfs_server}
      input_values:
        spool_mountpoint: { get_param: spool_mountpoint }
        spool_volid: { get_resource: spool_cinder_volume }
        srv_mountpoint:  { get_param: srv_mountpoint }
        srv_volid: { get_resource: srv_cinder_volume }

  #__________________________________
  # cvmfs server deployment
  cvmfs_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: vm_name }
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      availability_zone: { get_param: availability_zone }
      flavor: { get_param: instance_type }
      networks:
        - network: { get_param: net_id }
      security_groups: [ { get_resource: server_security_group } ]
      user_data_format: SOFTWARE_CONFIG

  #__________________________________
  # /var/spool/cvmfs volume
  spool_cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: spool_size }
      availability_zone: { get_param: availability_zone }

  spool_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: spool_cinder_volume }
      instance_uuid: { get_resource: cvmfs_server }
      mountpoint: null

  #__________________________________
  # /srv/cvmfs volume  
  srv_cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: srv_size }
      availability_zone: { get_param: availability_zone }

  srv_volume_attachment:
   type: OS::Cinder::VolumeAttachment
   properties:
     volume_id: { get_resource: srv_cinder_volume }
     instance_uuid: { get_resource: cvmfs_server }
     mountpoint: null

  #__________________________________
  # Security group  
  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 21
          port_range_max: 21
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80

##################################
outputs:
  vmIp:
    description: The IP address of the deployed instance
    value: { get_attr: [cvmfs_server, first_address] }
  vmUuid:
    description: Resource ID assigned to the newly created instance
    value: { get_resource: cvmfs_server }
  vmName:
    description: vm name 
    value: { get_param: vm_name }
  volumeUuid:
    description: Resource ID assigned to the newly created volume attached to instance
    value: { get_resource: spool_cinder_volume }
